/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CardioEquipmentRouteImport } from './routes/cardio-equipment'
import { Route as CommercialGymEquipmentRouteImport } from './routes/commercial-gym-equipment'
import { Route as FreeWeightsRouteImport } from './routes/free-weights'
import { Route as GymAccessoriesRouteImport } from './routes/gym-accessories'
import { Route as HomeGymEquipmentRouteImport } from './routes/home-gym-equipment'
import { Route as ShopEquipmentRouteImport } from './routes/shop-equipment'
import { Route as StrengthEquipmentRouteImport } from './routes/strength-equipment'
import { Route as UsedGymEquipmentRouteImport } from './routes/used-gym-equipment'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as CommercialGymEquipmentIndexRouteImport } from './routes/commercial-gym-equipment.index'
import { Route as CommercialGymEquipmentSolutionRouteImport } from './routes/commercial-gym-equipment.$solution'
import { Route as EquipmentSlugRouteImport } from './routes/equipment.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CardioEquipmentRoute = CardioEquipmentRouteImport.update({
  id: '/cardio-equipment',
  path: '/cardio-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialGymEquipmentRoute = CommercialGymEquipmentRouteImport.update({
  id: '/commercial-gym-equipment',
  path: '/commercial-gym-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeWeightsRoute = FreeWeightsRouteImport.update({
  id: '/free-weights',
  path: '/free-weights',
  getParentRoute: () => rootRouteImport,
} as any)
const GymAccessoriesRoute = GymAccessoriesRouteImport.update({
  id: '/gym-accessories',
  path: '/gym-accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeGymEquipmentRoute = HomeGymEquipmentRouteImport.update({
  id: '/home-gym-equipment',
  path: '/home-gym-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopEquipmentRoute = ShopEquipmentRouteImport.update({
  id: '/shop-equipment',
  path: '/shop-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const StrengthEquipmentRoute = StrengthEquipmentRouteImport.update({
  id: '/strength-equipment',
  path: '/strength-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const UsedGymEquipmentRoute = UsedGymEquipmentRouteImport.update({
  id: '/used-gym-equipment',
  path: '/used-gym-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const CommercialGymEquipmentIndexRoute =
  CommercialGymEquipmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CommercialGymEquipmentRoute,
  } as any)
const CommercialGymEquipmentSolutionRoute =
  CommercialGymEquipmentSolutionRouteImport.update({
    id: '/$solution',
    path: '/$solution',
    getParentRoute: () => CommercialGymEquipmentRoute,
  } as any)
const EquipmentSlugRoute = EquipmentSlugRouteImport.update({
  id: '/equipment/$slug',
  path: '/equipment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/cardio-equipment': typeof CardioEquipmentRoute
  '/commercial-gym-equipment': typeof CommercialGymEquipmentRouteWithChildren
  '/free-weights': typeof FreeWeightsRoute
  '/gym-accessories': typeof GymAccessoriesRoute
  '/home-gym-equipment': typeof HomeGymEquipmentRoute
  '/shop-equipment': typeof ShopEquipmentRoute
  '/strength-equipment': typeof StrengthEquipmentRoute
  '/used-gym-equipment': typeof UsedGymEquipmentRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/commercial-gym-equipment/$solution': typeof CommercialGymEquipmentSolutionRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/brands/': typeof BrandsIndexRoute
  '/commercial-gym-equipment/': typeof CommercialGymEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardio-equipment': typeof CardioEquipmentRoute
  '/free-weights': typeof FreeWeightsRoute
  '/gym-accessories': typeof GymAccessoriesRoute
  '/home-gym-equipment': typeof HomeGymEquipmentRoute
  '/shop-equipment': typeof ShopEquipmentRoute
  '/strength-equipment': typeof StrengthEquipmentRoute
  '/used-gym-equipment': typeof UsedGymEquipmentRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/commercial-gym-equipment/$solution': typeof CommercialGymEquipmentSolutionRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/brands': typeof BrandsIndexRoute
  '/commercial-gym-equipment': typeof CommercialGymEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/cardio-equipment': typeof CardioEquipmentRoute
  '/commercial-gym-equipment': typeof CommercialGymEquipmentRouteWithChildren
  '/free-weights': typeof FreeWeightsRoute
  '/gym-accessories': typeof GymAccessoriesRoute
  '/home-gym-equipment': typeof HomeGymEquipmentRoute
  '/shop-equipment': typeof ShopEquipmentRoute
  '/strength-equipment': typeof StrengthEquipmentRoute
  '/used-gym-equipment': typeof UsedGymEquipmentRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/commercial-gym-equipment/$solution': typeof CommercialGymEquipmentSolutionRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/brands/': typeof BrandsIndexRoute
  '/commercial-gym-equipment/': typeof CommercialGymEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/cardio-equipment'
    | '/commercial-gym-equipment'
    | '/free-weights'
    | '/gym-accessories'
    | '/home-gym-equipment'
    | '/shop-equipment'
    | '/strength-equipment'
    | '/used-gym-equipment'
    | '/brands/$slug'
    | '/commercial-gym-equipment/$solution'
    | '/equipment/$slug'
    | '/brands/'
    | '/commercial-gym-equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardio-equipment'
    | '/free-weights'
    | '/gym-accessories'
    | '/home-gym-equipment'
    | '/shop-equipment'
    | '/strength-equipment'
    | '/used-gym-equipment'
    | '/brands/$slug'
    | '/commercial-gym-equipment/$solution'
    | '/equipment/$slug'
    | '/brands'
    | '/commercial-gym-equipment'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/cardio-equipment'
    | '/commercial-gym-equipment'
    | '/free-weights'
    | '/gym-accessories'
    | '/home-gym-equipment'
    | '/shop-equipment'
    | '/strength-equipment'
    | '/used-gym-equipment'
    | '/brands/$slug'
    | '/commercial-gym-equipment/$solution'
    | '/equipment/$slug'
    | '/brands/'
    | '/commercial-gym-equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  CardioEquipmentRoute: typeof CardioEquipmentRoute
  CommercialGymEquipmentRoute: typeof CommercialGymEquipmentRouteWithChildren
  FreeWeightsRoute: typeof FreeWeightsRoute
  GymAccessoriesRoute: typeof GymAccessoriesRoute
  HomeGymEquipmentRoute: typeof HomeGymEquipmentRoute
  ShopEquipmentRoute: typeof ShopEquipmentRoute
  StrengthEquipmentRoute: typeof StrengthEquipmentRoute
  UsedGymEquipmentRoute: typeof UsedGymEquipmentRoute
  EquipmentSlugRoute: typeof EquipmentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardio-equipment': {
      id: '/cardio-equipment'
      path: '/cardio-equipment'
      fullPath: '/cardio-equipment'
      preLoaderRoute: typeof CardioEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-gym-equipment': {
      id: '/commercial-gym-equipment'
      path: '/commercial-gym-equipment'
      fullPath: '/commercial-gym-equipment'
      preLoaderRoute: typeof CommercialGymEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-weights': {
      id: '/free-weights'
      path: '/free-weights'
      fullPath: '/free-weights'
      preLoaderRoute: typeof FreeWeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-accessories': {
      id: '/gym-accessories'
      path: '/gym-accessories'
      fullPath: '/gym-accessories'
      preLoaderRoute: typeof GymAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-gym-equipment': {
      id: '/home-gym-equipment'
      path: '/home-gym-equipment'
      fullPath: '/home-gym-equipment'
      preLoaderRoute: typeof HomeGymEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-equipment': {
      id: '/shop-equipment'
      path: '/shop-equipment'
      fullPath: '/shop-equipment'
      preLoaderRoute: typeof ShopEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strength-equipment': {
      id: '/strength-equipment'
      path: '/strength-equipment'
      fullPath: '/strength-equipment'
      preLoaderRoute: typeof StrengthEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/used-gym-equipment': {
      id: '/used-gym-equipment'
      path: '/used-gym-equipment'
      fullPath: '/used-gym-equipment'
      preLoaderRoute: typeof UsedGymEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/commercial-gym-equipment/': {
      id: '/commercial-gym-equipment/'
      path: '/'
      fullPath: '/commercial-gym-equipment/'
      preLoaderRoute: typeof CommercialGymEquipmentIndexRouteImport
      parentRoute: typeof CommercialGymEquipmentRoute
    }
    '/commercial-gym-equipment/$solution': {
      id: '/commercial-gym-equipment/$solution'
      path: '/$solution'
      fullPath: '/commercial-gym-equipment/$solution'
      preLoaderRoute: typeof CommercialGymEquipmentSolutionRouteImport
      parentRoute: typeof CommercialGymEquipmentRoute
    }
    '/equipment/$slug': {
      id: '/equipment/$slug'
      path: '/equipment/$slug'
      fullPath: '/equipment/$slug'
      preLoaderRoute: typeof EquipmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface CommercialGymEquipmentRouteChildren {
  CommercialGymEquipmentSolutionRoute: typeof CommercialGymEquipmentSolutionRoute
  CommercialGymEquipmentIndexRoute: typeof CommercialGymEquipmentIndexRoute
}

const CommercialGymEquipmentRouteChildren: CommercialGymEquipmentRouteChildren =
  {
    CommercialGymEquipmentSolutionRoute: CommercialGymEquipmentSolutionRoute,
    CommercialGymEquipmentIndexRoute: CommercialGymEquipmentIndexRoute,
  }

const CommercialGymEquipmentRouteWithChildren =
  CommercialGymEquipmentRoute._addFileChildren(
    CommercialGymEquipmentRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRouteWithChildren,
  CardioEquipmentRoute: CardioEquipmentRoute,
  CommercialGymEquipmentRoute: CommercialGymEquipmentRouteWithChildren,
  FreeWeightsRoute: FreeWeightsRoute,
  GymAccessoriesRoute: GymAccessoriesRoute,
  HomeGymEquipmentRoute: HomeGymEquipmentRoute,
  ShopEquipmentRoute: ShopEquipmentRoute,
  StrengthEquipmentRoute: StrengthEquipmentRoute,
  UsedGymEquipmentRoute: UsedGymEquipmentRoute,
  EquipmentSlugRoute: EquipmentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
